### ISSUE TITLE
Error when implementing `Header` component.

### ISSUE THREAD

**Issue by harrymaynard-maximus** [bcgov/vue-shared-components#20]
**Describe the bug**
Error in console when implementing the `Header` component.
```
[Vue warn]: Invalid prop: type check failed for prop "width". Expected Number with value 181, got String with value "181".

found in

---> <HeadingImage> at vue-shared-components/src/components/header/HeadingImage.vue
       <Header> at vue-shared-components/src/components/header/Header.vue
```

**To Reproduce**
Implement the `Header` component into an application.

**Expected behavior**
Should not throw an error.

**Screenshots**

**Desktop:**
 - OS: Linux
 - Browser Chrome
 - Version 80

**Additional context**
Need to use `v-bind` instead of string literal when passing width prop.

May I please get write access to this repository, so that I can submit a pull request to fix this bug. - @harrymaynard-maximus

**Comment by sdevalapurkar-bcgov** [comment]
@harrymaynard-maximus thank you for this :) first issue!! so exciting! I have granted you write access

**Comment by akroon3r** [comment]
🎂

**Comment by sdevalapurkar-bcgov** [comment]
fixed with https://github.com/bcgov/vue-shared-components/pull/29
